apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana-ingress.yaml
  - prometheus-ingress.yaml
  - networkpolicy.yaml
  - grafana-loki-datasource.yaml
  - grafana-loki-dashboard.yaml
  - grafana-security-dashboard.yaml
  - healthcare-alerts.yaml
  - postgres-exporter.yaml
  - pgadmin.yaml
  - grafana-postgres-dashboard.yaml
