sonar.projectKey=hutusnov_healthcare
sonar.organization=hutusnov
sonar.projectName=UIT Healthcare
sonar.sources=BACK-END/PROJECT-TEST/src,OCR
sonar.exclusions=**/node_modules/**,**/dist/**,**/.venv/**,**/venv/**,APP-ANDROID/**,OCR/Dockerfile
sonar.python.version=3.12
sonar.coverage.exclusions=**/*
