#!/usr/bin/env python3
"""
Script sinh/cập nhật inventory/hosts.yml từ terraform output -json.

Chạy sau khi `terraform apply` hoặc khi IP thay đổi:
  python3 scripts/gen_inventory_from_tf.py

Script sẽ ghi đè phần ansible_host trong hosts.yml nhưng giữ nguyên các vars khác.
"""

import json
import subprocess
import sys
import os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ANSIBLE_DIR = os.path.dirname(SCRIPT_DIR)
TF_DIR = os.path.join(SCRIPT_DIR, "..", "..", "terraform-openstack", "envs", "dev")
HOSTS_FILE = os.path.join(ANSIBLE_DIR, "inventory", "hosts.yml")

WIREGUARD_IPS = {
    "k3s-master-vpn": "10.10.0.1",
    "data-core-node": "10.10.0.2",
    "ai-ocr-worker":  "10.10.0.3",
}

K3S_ROLES = {
    "k3s-master-vpn": "master",
    "data-core-node": "worker",
    "ai-ocr-worker":  "worker",
}


def get_tf_output():
    print(f"[*] Running terraform output in {TF_DIR} ...")
    result = subprocess.run(
        ["terraform", "output", "-json"],
        capture_output=True, text=True, cwd=TF_DIR
    )
    if result.returncode != 0:
        print(f"[!] terraform output failed:\n{result.stderr}", file=sys.stderr)
        sys.exit(1)
    return json.loads(result.stdout)


def extract_nodes(tf_out):
    inventory_val = tf_out.get("openstack_adopted_inventory", {}).get("value", {})
    instances = inventory_val.get("instances", {})
    nodes = {}
    for role_key, inst in instances.items():
        if not inst:
            print(f"  [!] {role_key}: no data (not adopted yet)")
            continue
        name = inst.get("name", "")
        ip = inst.get("fixed_ip", "")
        state = inst.get("power_state", "unknown")
        if name:
            nodes[name] = {"ip": ip or "FILL_ME", "state": state}
            status = ip if ip else "IP not in terraform output yet"
            print(f"  [+] {name}: {status} (state={state})")
    return nodes


def generate_hosts_yml(nodes):
    masters = {n: d for n, d in nodes.items() if K3S_ROLES.get(n) == "master"}
    workers = {n: d for n, d in nodes.items() if K3S_ROLES.get(n) != "master"}

    lines = [
        "# AUTO-GENERATED by scripts/gen_inventory_from_tf.py — do not edit manually",
        "# Re-run the script after terraform apply to refresh IPs.",
        "",
        "all:",
        "  vars:",
        "    ansible_user: ubuntu",
        "    ansible_ssh_private_key_file: ~/.ssh/id_rsa",
        "    ansible_python_interpreter: /usr/bin/python3",
        "",
        "k3s_cluster:",
        "  children:",
        "    k3s_master:",
        "      hosts:",
    ]

    for name, data in masters.items():
        lines += [
            f"        {name}:",
            f"          ansible_host: {data['ip']}",
            f"          wireguard_ip: {WIREGUARD_IPS.get(name, 'FILL_ME')}",
            f"          k3s_role: master",
        ]

    lines += [
        "    k3s_workers:",
        "      hosts:",
    ]

    for name, data in workers.items():
        lines += [
            f"        {name}:",
            f"          ansible_host: {data['ip']}",
            f"          wireguard_ip: {WIREGUARD_IPS.get(name, 'FILL_ME')}",
            f"          k3s_role: worker",
        ]

    return "\n".join(lines) + "\n"


def main():
    tf_out = get_tf_output()
    nodes = extract_nodes(tf_out)

    if not nodes:
        print("[!] No instances found in terraform output. Check that IDs are set in terraform.tfvars.")
        sys.exit(1)

    content = generate_hosts_yml(nodes)

    with open(HOSTS_FILE, "w") as f:
        f.write(content)

    print(f"\n[✓] Written: {HOSTS_FILE}")
    print("\nVerify with:")
    print("  ansible-inventory -i inventory/hosts.yml --list")


if __name__ == "__main__":
    main()
