apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uit-healthcare-aws-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hutusnov/healthcare.git
    targetRevision: main
    path: deploy/gitops/apps/aws-backend/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: uit-healthcare-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
