all:
  vars:
    env: staging
    ansible_user: ubuntu
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_private_key_file: ~/.ssh/healthcare-staging
    ansible_ssh_common_args: >-
      -o StrictHostKeyChecking=no
      -o ConnectTimeout=10
      -o ServerAliveInterval=30
    secret_source: aws_secrets_manager
    aws_profile: healthcare-staging
    aws_region: ap-southeast-2
    aws_cli_path: /mnt/c/Program Files/Amazon/AWSCLIV2/aws.exe
    backend_secret_id: uit-healthcare-staging/backend
    backend_root: /opt/healthcare-backend
    db_container_name: healthcare-postgres
    db_name: project_test
    db_user: postgres
    db_backup_root: /opt/healthcare-backend/backups
  children:
    staging:
      children:
        staging_aws:
          children:
            staging_backend_nodes:
              hosts:
                staging-backend-az1:
                  ansible_host: 3.104.77.131
                  role: backend
                staging-backend-az2:
                  ansible_host: 15.134.185.191
                  role: backend
        linux_nodes:
          children:
            staging_backend_nodes:
        backend_nodes:
          children:
            staging_backend_nodes:
        k3s_master:
          hosts: {}
        k3s_workers:
          hosts: {}
