apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: uit-healthcare-private
resources:
  - ../../base
images:
  - name: placeholder.local/healthcare-ocr
    newName: ghcr.io/hutusnov/healthcare-ocr
    newTag: 8953464fd7196dea17e82cdf367f5c285b39551b
