apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: uit-healthcare-private
resources:
- ../../base
images:
- name: healthcare-ocr
  newName: ghcr.io/hutusnov/healthcare-ocr
  newTag: cd70a41ee6723954de4461d45cb30a574a27cfb6
- name: placeholder.local/healthcare-ocr
  newName: ghcr.io/hutusnov/healthcare-ocr
  newTag: 8d5c9a5e10c1e25f28648f1ad4336eff64a7d545
