apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-runtime-secret
  namespace: uit-healthcare-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: backend-runtime-secret
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: uit-healthcare-staging/backend
        property: backend_jwt_secret
    - secretKey: DB_PASSWORD
      remoteRef:
        key: uit-healthcare-staging/backend
        property: db_password
