apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secretsmanager
  namespace: uit-healthcare-prod
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-southeast-2
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-secretsmanager-reader
            key: access-key-id
          secretAccessKeySecretRef:
            name: aws-secretsmanager-reader
            key: secret-access-key

