apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: uit-healthcare-prod
resources:
- ../../base
images:
- name: healthcare-backend
  newName: ghcr.io/hutusnov/healthcare-backend
  newTag: def8169520d823d3ff83047ac5d39a6fa1633452
- name: placeholder.local/healthcare-backend
  newName: ghcr.io/hutusnov/healthcare-backend
  newTag: 8d5c9a5e10c1e25f28648f1ad4336eff64a7d545
