apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: uit-healthcare-prod
resources:
  - ../../base
images:
  - name: placeholder.local/healthcare-backend
    newName: ghcr.io/hutusnov/healthcare-backend
    newTag: 846d53b4acc1b136fe70525733d5361541ab7bc5
