apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: uit-healthcare-prod
resources:
- ../../base
images:
- name: healthcare-backend
  newName: ghcr.io/hutusnov/healthcare-backend
  newTag: 167488b20d34480bcf07a570d3513a039fbfda53
- name: placeholder.local/healthcare-backend
  newName: ghcr.io/hutusnov/healthcare-backend
  newTag: 8d5c9a5e10c1e25f28648f1ad4336eff64a7d545
