apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uit-healthcare-loki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  labels:
    app.kubernetes.io/part-of: uit-healthcare
    app.kubernetes.io/managed-by: argocd
spec:
  project: uit-healthcare
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki-stack
    targetRevision: "2.10.3"
    helm:
      values: |
        grafana:
          enabled: false
        prometheus:
          enabled: false
        promtail:
          enabled: true
        loki:
          persistence:
            enabled: true
            size: 10Gi
          config:
            limits_config:
              retention_period: 168h
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
