apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uit-healthcare-openstack-monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  labels:
    app.kubernetes.io/part-of: uit-healthcare
    app.kubernetes.io/managed-by: argocd
spec:
  project: uit-healthcare
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 83.0.0
    helm:
      releaseName: o11y
      values: |
        grafana:
          admin:
            existingSecret: o11y-grafana
            userKey: admin-user
            passwordKey: admin-password
          nodeSelector:
            kubernetes.io/hostname: data-core-node

        prometheus:
          prometheusSpec:
            nodeSelector:
              kubernetes.io/hostname: data-core-node

        alertmanager:
          alertmanagerSpec:
            nodeSelector:
              kubernetes.io/hostname: data-core-node

        prometheusOperator:
          nodeSelector:
            kubernetes.io/hostname: data-core-node

        kube-state-metrics:
          nodeSelector:
            kubernetes.io/hostname: data-core-node

        prometheus-node-exporter:
          hostNetwork: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: o11y-grafana
      namespace: monitoring
      jsonPointers:
        - /data
    - group: apps
      kind: Deployment
      name: o11y-grafana
      namespace: monitoring
      jsonPointers:
        - /spec/template/metadata/annotations/checksum~1secret
