apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backend-api-ingress
spec:
  podSelector:
    matchLabels:
      app: backend-api
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 4000
