name: CI Admin Panel

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_call:
  workflow_dispatch:

jobs:
  validate-admin-panel:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: BACK-END/PROJECT-TEST/admin-panel
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: BACK-END/PROJECT-TEST/admin-panel/package-lock.json
      - run: npm ci
      - run: npm run lint
      - run: npm run build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_X_SECRET_VERIFY_HEADER: ${{ secrets.X_SECRET_VERIFY_HEADER }}



  notify:
    name: Notify Telegram
    if: always()
    needs: [validate-admin-panel]
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            🚀 Workflow: ${{ github.workflow }}
            👤 Actor: ${{ github.actor }}
            📝 Commit: ${{ github.sha }}
            📊 Status: ${{ job.status }}
            🔗 Link: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
